ForumDisscussion/Controllers/UserHomePageController.cs
using System;

using System.Data;
using System.Linq;

using System.Web.Mvc;

using ForumDisscussion.Models;

namespace ForumDisscussion.Controllers
{
    public class UserHomePageController : Controller
    {
        readonly ForumDataBaseConnectionContext _db = new ForumDataBaseConnectionContext();


        Questions _question = new Questions();
        Comment comment = new Comment();
        [Authorize]
        public ActionResult UserAnsQuestionList()
        {


            int authUserId = _db.ForumUser.Single(m => m.UserName.Equals(User.Identity.Name)).UserId;
            ViewData["ProfileInfo"] = from u in _db.ForumUser
                                      where u.UserId == authUserId
                                      select new ForumUser()
                                          {
                                              FirstName = u.FirstName,
                                              LastName = u.LastName,
                                              UserName = u.UserName,
                                              Country = u.Country,
                                              Email = u.Email
                                          };
       
                                           
            return View(_db.ForumUser.Where(m=>m.UserName.Equals(User.Identity.Name)).ToList());




        }

        public ActionResult PostComment(int id = 0)
        {
            ViewData["op"] = 9;
            DisplayAnswerAndPostedUserInfo(id);
            DisplayComments(id);
            return View("Comments");
        }
        private void DisplayAnswerAndPostedUserInfo(int id)
        {
            ViewData["Query"] = (from a in _db.Answers
                                 join u in _db.ForumUser on a.UserId equals u.UserId
                                 where a.AnswerId.Equals(id)
                                 select new AnsPostedUser() { Image = u.Image, Username = u.UserName, PostedDate = a.AnsweredTimeDate, Answer = a.Answer });
            ViewBag.totalComments = _db.Comment.Count(m => m.AnswerId.Equals(id));

        }

        private void DisplayComments(int id)
        {
            ViewData["Comments"] = (from c in _db.Comment
                                    join u in _db.ForumUser on c.UserId equals u.UserId
                                    where c.AnswerId.Equals(id)
                                    select new UserComment() { CommentMsg = c.CommentMsg, Username = u.UserName, Image = u.Image, PostedDate = c.PostedDateTime }).ToList();




        }
        [HttpPost]
        public ActionResult PostComment(int? id, string msg)
        {
            var u = _db.ForumUser.SingleOrDefault(m => m.UserName.Equals(User.Identity.Name));
            if (u == null) return View("Comments");
            var userId = u.UserId;
            if (id == null) return View("Comments");
            DisplayAnswerAndPostedUserInfo(id.Value);
            DisplayComments(id.Value);
            ViewData["op"] = 9;

            if (msg != "")
            {

                if (msg.Length >= 3)
                {
                    comment.CommentMsg = msg;
                    comment.UserId = userId;
                    comment.AnswerId = id.Value;
                    comment.PostedDateTime = DateTime.Now;
                    _db.Comment.Add(comment);
                    _db.SaveChanges();
                    DisplayComments(id.Value);
                    UpdateTotComments(id.Value);
                    DisplayAnswerAndPostedUserInfo(id.Value);
                }

                else
                {
                    ViewData["ReqMsg"] = 1;
                    ViewBag.errormsg = "* Comment should not contain less than 3 chracters.";
                }

            }

            else
            {
                ViewData["ReqMsg"] = 1;
                ViewBag.errormsg = "* You must Write Something! to Post  comment";


            }


            return View("Comments");
        }

      

        private void UpdateTotComments(int id)
        {
            var v = _db.Answers.SingleOrDefault(x => x.AnswerId.Equals(id));
            if (v != null)
            {
                if (v.Comments != null)
                {
                    var totComts = v.Comments.Value;
                    var answer = _db.Answers.Single(m => m.AnswerId.Equals(id));
                    answer.Comments = totComts + 1;
                    _db.Entry(answer).State = EntityState.Modified;
                }
            }
            _db.SaveChanges();


        }

               public ActionResult UpdateImage()
               {

                   return View();
               }
                [HttpPost]
               public ActionResult UpdateImage(ImageUpdateViewModel m)
               {
                    if (!ModelState.IsValid) return View();
                    var c = _db.ForumUser.SingleOrDefault(u => u.UserName.Equals(User.Identity.Name));
                    if (c != null)
                    {
                        var authUserId = c.UserId;
                        var usr = _db.ForumUser.Find(authUserId);
                        var data = new byte[m.File.ContentLength];
                        m.File.InputStream.Read(data, 0, m.File.ContentLength);
                        m.Image = data;

                        usr.Image = m.Image;
                        _db.Entry(usr).State=EntityState.Modified;
                    }
                    _db.SaveChanges();
                    ViewBag.imgUpSuccessId = 1;
                    return View();
               }

        public ActionResult UpdatePassword()
        {
          

            return View();

        }



        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdatePassword(UserPasswordUpdateModel model)
        {
            if (!ModelState.IsValid) return View();
            var v = _db.ForumUser.SingleOrDefault(m => m.UserName.Equals(User.Identity.Name));
            if (v == null) return View();
            var id = v.UserId;
            var checkOldPassword = _db.ForumUser.SingleOrDefault(m=>m.UserId.Equals(id)&&m.Password.Equals(model.OldPassword));
            if (checkOldPassword!=null)
            {
                var u = _db.ForumUser.Find(id);
                u.Password = model.NewPassword;
                _db.Entry(u).State=EntityState.Modified;
                _db.SaveChanges();
                ViewBag.successMs =1;
            }
            else
            {
                ModelState.AddModelError("","* Sorry,Your entered password do not match with your old password!");
            }

            return View();

            }
        }
    }

ForumDisscussion/Views/UserHomePage/UpdateImage.cshtml
@using ForumDisscussion.Models
@model ForumDisscussion.Models.ImageUpdateViewModel
@{
    ViewBag.Title = "Update Image";
}
<link href="~/jQxWidegets/jqx.base.css" rel="stylesheet" />
<link href="~/CSS/gh-buttons.css" rel="stylesheet" />
<script src="~/jQxWidegets/jquery-1.11.1.min.js"></script>
<style>

     #imgUpButton{width: 100px}
</style>

<h2>UpdateImage</h2>
@section Scripts
{
   
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.imgareaselect.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.fancyupload.js")"></script>
  
    <script>
        $(document).ready(function () {
            initSelect();
        });
    </script>
     

}
 <script src="~/KendoUI/jquery.min.js"></script>
     <script src="~/KendoUI/kendo.all.min.js"></script>
@using (Html.BeginForm("UpdateImage", "UserHomePage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
        
       
                   <img alt="Field for image cutting" width="100"  id="preview" src="@Url.Content("~/Content/empty.png")" />
   
    <table>
        <tr>
            <td>
                Select New Image &nbsp;
            </td>
            <td>
                @Html.FileFor(model => model.File) 
            </td>
           <td>&nbsp; @Html.ValidationMessageFor(model => model.File)</td>
        </tr>
 
        <tr>
          
            <td></td>
            <td>
            
                <input type="submit" value="Save" class="btn" id="imgUpButton" />
                @Html.ActionLink("Back", "UserAnsQuestionList", "UserHomePage", new { area = "" }, new { @class = "button icon arrowleft  backLink bakToHom" })
             </td>
        </tr>

    </table>
    
 
          
      
 
  
}

<input type="text" value="@ViewBag.imgUpSuccessId" id="imgSuccessDiaId" style="display: none"/>

<div id="successMessageReferenceDiv"> </div>



<script>


    function displaySuccessMessage(text) {
        $("#successMessageReferenceDiv").html('<h4>' + text + '</h4>').fadeIn().delay(3000).fadeOut();

    }
    if ($("#imgSuccessDiaId").val() == 1) {

        displaySuccessMessage(' <img src="/Png/1405880759_accepted_48.png" width="35" /> Thanks!. Your Image has been updated successfully.');
    
    }
</script>

ForumDisscussion/Views/UserHomePage/UpdatePassword.cshtml
@model ForumDisscussion.Models.UserPasswordUpdateModel

@{
    ViewBag.Title = "UpdatePassword";
}

<style>
    .btn{width: 90px}
</style>
<link href="~/CSS/gh-buttons.css" rel="stylesheet" />

<script src="~/KendoUI/kendo.all.min.js"></script>
<h2>Update Password</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserPasswordUpdateModel</legend>

        <div class="editor-label">
           Old Password
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OldPassword)
            @Html.ValidationMessageFor(model => model.OldPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NewPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NewPassword)
            @Html.ValidationMessageFor(model => model.NewPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ConfirmNewPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ConfirmNewPassword)
            @Html.ValidationMessageFor(model => model.ConfirmNewPassword)
        </div>
        <br/>
        <p>
            <input type="submit" value="Update" class="btn btn-primary color" />
            @Html.ActionLink("Back", "UserAnsQuestionList", "UserHomePage", new { @class = "button icon arrowleft  backLink bakToHom" })
        </p>
    </fieldset>
}
<div id="successMessageReferenceDiv"> </div>

<div id="succDialog" style="visibility: hidden">
    <img src="~/Png/1405880759_accepted_48.png" width="35"/>
    Your  Password Updated Successfully.
</div>
<input type="text" value="@ViewBag.successMs" id="successId" style="display: none"/>
<script>
    function displaySuccessMessage(text) {
        $("#successMessageReferenceDiv").html('<h4>' + text + '</h4>').fadeIn().delay(3000).fadeOut();

    }
    if ($("#successId").val()==1) {
     
        displaySuccessMessage('     <img src="/Png/1405880759_accepted_48.png" width="35" /> Thanks!. Your <b>password</b> has been <b>changed</b> successfully.');

    }
    $(".color").css('color', 'white');


</script>

ForumDisscussion/Views/UserHomePage/UserAnsQuestionL.cshtml
@model IEnumerable<ForumDisscussion.Models.UserPostedQuestion>

@{
    ViewBag.Title = "UserAnsQuestionL";
}

<h2>UserAnsQuestionL</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Question)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnsUserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Answer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReplyUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Question)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnsUserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Answer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReplyUser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostedDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>