ForumDisscussion/Controllers/UserQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ForumDisscussion.Models;
using PagedList;


namespace ForumDisscussion.Controllers
{

    public class UserQuestionsController : Controller
    {
        readonly ForumDataBaseConnectionContext _db = new ForumDataBaseConnectionContext();


        public ActionResult PostQuestion()
        {

            try
            {
                if (!Request.IsAuthenticated)
                {
                    ViewBag.authErrorState = 402;

                    TempData["UQC"] = 3;
                }
                if (Request.IsAuthenticated)
                {

                    ViewBag.authErrorState = null;
                }
                ViewBag.cs = _db.Category.Select(m => m.CategoryName);

                var u = new ForumUser();

                var categories = _db.Category.Select(c => new
                {
                    CategoryID = c.CategoryId,

                    Category = c.CategoryName
                }).ToList();

                ViewBag.Categories = new SelectList(categories, "CategoryID", "Category");


                ViewData["QuestionLists"] = (_db.Questions.Join(_db.ForumUser, q => q.UserId, us => us.UserId,
                    (q, us) => new {q, us})
                    .Join(_db.Category, @t => @t.q.CategoryId, c => c.CategoryId, (@t, c) => new {@t, c})
                    .OrderByDescending(@t => @t.@t.q.PostedDate)
                    .Select(@t => new QuestionList()
                    {
                        Question = @t.@t.q.Question,
                        Image = @t.@t.us.Image,
                        PostedBy = @t.@t.us.UserName,
                        Posteddate = @t.@t.q.PostedDate,
                        Category = @t.c.CategoryName,
                        Answers = @t.@t.q.answers,
                        Views = @t.@t.q.views,
                        Id = @t.@t.q.QuestionId
                    }));
            }
            catch (Exception e)
            {

            }



            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult PostQuestion(QuestionPostModel model)
        {
            if (Request.IsAuthenticated)
            {

                if (ModelState.IsValid)
                {
                    try
                    {

                        var checkQuestionIsExist = _db.Questions.Any(m => m.Question.Equals(model.QuestionMessage));
                        if (!checkQuestionIsExist)
                        {
                            var u = _db.ForumUser.FirstOrDefault(m => m.UserName.Equals(User.Identity.Name));
                            if (u != null)
                            {
                                var userId = u.UserId;
                                var userQuestions = new Questions
                                {
                                    PostedDate = DateTime.Now,
                                    Question = model.QuestionMessage,
                                    CategoryId = Convert.ToInt32(model.Category),
                                    UserId = userId,
                                    answers = 0,
                                    views = 0
                                };


                                _db.Questions.Add(userQuestions);
                                _db.SaveChanges();
                                var v = _db.PostInformation.SingleOrDefault(m => m.UserId.Equals(userId));
                                if (v != null)
                                {
                                    var posId = v.PostId;
                                    var totalQuesPost = _db.PostInformation.Find(posId).TotalQuesPost;
                                    if (totalQuesPost != null)
                                    {
                                        var prevPosts = totalQuesPost.Value;
                                        var pi = _db.PostInformation.Find(posId);


                                        pi.TotalQuesPost = prevPosts + 1;

                                        _db.Entry(pi).State = EntityState.Modified;
                                    }
                                }
                            }
                            _db.SaveChanges();

                            ViewData["unLUQC"] = 4;
                            ViewData["QuestionLists"] = (from q in _db.Questions

                                                         join us in _db.ForumUser on q.UserId equals us.UserId
                                                         join c in _db.Category on q.CategoryId equals c.CategoryId
                                                         orderby q.QuestionId descending



                                                         select
                                                             new QuestionList()
                                                             {
                                                                 Question = q.Question,
                                                                 Image = us.Image,
                                                                 PostedBy = us.UserName,
                                                                 Posteddate = q.PostedDate,
                                                                 Category = c.CategoryName,
                                                                 Answers = q.answers,
                                                                 Views = q.views,
                                                                 Id = q.QuestionId
                                                             });
                            var categories = _db.Category.Select(c => new
                            {
                                CategoryID = c.CategoryId,
                                CategoryName = c.CategoryName
                            }).OrderByDescending(m => m.CategoryID).ToList();
                            ViewBag.Categories = new MultiSelectList(categories, "CategoryID", "");



                            Response.Write("<div id='op'></div>");
                        }
                        else
                        {
                            ModelState.AddModelError("","It seems that this question already exist.");
                        }
                  
                    }
                    catch (Exception e)
                    {

                        
                    }


                }

                ViewData["QuestionLists"] = (_db.Questions.Join(_db.ForumUser, q => q.UserId, us => us.UserId,
                    (q, us) => new {q, us})
                    .Join(_db.Category, @t => @t.q.CategoryId, c => c.CategoryId, (@t, c) => new QuestionList()
                    {
                        Question = @t.q.Question,
                        Image = @t.us.Image,
                        PostedBy = @t.us.UserName,
                        Posteddate = @t.q.PostedDate,
                        Category = c.CategoryName,
                        Answers = @t.q.answers,
                        Views = @t.q.views,
                        Id = @t.q.QuestionId
                    })).OrderByDescending(m => m.Id);



                var cates = _db.Category.Select(c => new
                {
                    CategoryID = c.CategoryId,
                    CategoryName = c.CategoryName


                }).ToList();

                ViewBag.Categories = new SelectList(cates, "CategoryID", "CategoryName", Convert.ToInt32(model.Category).ToString());





            }
            else
            {
                ViewBag.authErrorState = 402;
                TempData["UQC"] = 3;
            }



            return View(model);

        }


    }
}

ForumDisscussion/Views/UserQuestions/PostQuestion.cshtml
@using ForumDisscussion.Models
@model QuestionPostModel
@{
    ViewBag.Title = "PostQuestion";
}
<style>#msgBox{ height: 400px;width:580px}</style>



<script src="~/KendoUI/jquery.min.js"></script>
<link href="~/KendoUI/kendo.common.min.css" rel="stylesheet" />
<link href="~/KendoUI/kendo.dataviz.min.css" rel="stylesheet" />
<link href="~/KendoUI/kendo.default.min.css" rel="stylesheet" />
<link href="~/KendoUI/kendo.rtl.min.css" rel="stylesheet" />
<script src="~/KendoUI/kendo.all.min.js"></script>
@{



    var scrollPositionX = string.Empty;
    if (IsPost)
    {
        scrollPositionX = Request.Form["ScrollPositionX"];

    }


}
<input id="logC" type="text" value="@ViewData["unLUQC"]" style="display: none" />
<input type="text" value="@ViewBag.authErrorState" id="loginWarning" style="display: none" />


@Html.Partial("_DisplayQuestions")

@using (Html.BeginForm("PostQuestion", "UserQuestions", FormMethod.Post, new { id = "ticketsForm" }))
{



    <div id="pagLink">


    </div>

    <div id="postQuesPa">
        Post Your Question
        <img src="~/Png/qu.jpg" width="60" />

    </div>
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Question</legend>

        <p>




        </p>
        <div class="editor-label">
            Category
        </div>

        <div class="editor-field">
            <span>
                @Html.DropDownList("Category", (MultiSelectList)ViewBag.Categories, "Select Category", new { id = "me" })
                @if (ViewBag.authErrorState != 402)
                {
                    @Html.ValidationMessageFor(model => model.Category)

                }

            </span>


            <br />


            <br />




        </div>
        <div class="editor-field">
        </div>

        <div class="editor-label">
            Question
        </div>
        <div class="editor-field">
            @ViewBag.t
            @Html.TextAreaFor(model => model.QuestionMessage, new { id = "msgBox", @class = "ansBox emptyQuestionBox" })

            @if (ViewBag.authErrorState != 402)
            {
                @Html.ValidationMessageFor(model => model.QuestionMessage)

            }

        </div>



        <br />

        <p>


            <input type="submit" value="POST" class="btn btn-info" id="quesPostButton" />

            <input type="hidden" id="ScrollPositionX" name="ScrollPositionX" value="@scrollPositionX" />



        </p>
        <p class="status"></p>
    </fieldset>
}

<div id="UnAuthUserErr" style="visibility: hidden">



    <span id="unauthDialog">

        <img src="~/Png/alert.png" width="40" />
        It seems you are not <strong>logged in</strong>. You must have to <strong><u>@Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "logLink" })</u></strong> to Post  a <strong>Question</strong>.Without <b>login</b> you cann't <b>Post</b> Question
    </span>
    <div>

    </div>



</div>

<script>


  
    $(".quesLink").css('background', 'none');
    $("#k").kendoGrid({


        pageable: {
            refresh: true,
            pageSizes: true,
            buttonCount: 5
        }

           , dataSource: { pageSize: 5 }

           ,

        scrollable: false
           ,
        sortable: true,
        filterable: true,
        columnMenu: false,
        serverPaging: true,
        type: "odata"
    });


  
    $(function () {
      
        $("#quesPostButton").css('color', 'white');
    });

    var erroec = $("#loginWarning").val();

    if (erroec == 402) {

        $("#quesPostButton").attr('disabled', true);


        $("#UnAuthUserErr").kendoWindow({
            position: {
                top: "30%",
                left: "30%"
            }, title: "Login Warning Dialog", height: 100, width: 600
        });

      

    }

</script>

ForumDisscussion/Views/UserQuestions/_DisplayQuestions.cshtml
@using ForumDisscussion.Models

<h2>PostQuestion</h2>

<table id="k">
    <tr>
        <th data-sortable="false" data-menuable="false" data-filterable="false">
            Question
        </th>
        <th data-sortable="false" data-menuable="false" data-filterable="false">
            Category
        </th>
        <th data-sortable="false" data-menuable="false" data-filterable="false">
            Views
        </th>
        <th data-sortable="false" data-menuable="false" data-filterable="false">
            Replies
        </th>
    </tr>

    @foreach (var item in (IEnumerable<QuestionList>)ViewData["QuestionLists"])
    {
        <tr>
            <td>
                <div id="homQues">
                    <img src="~/Png/question_balloon(1).png" width="35" />
                    <a href="@Url.Action("PostAnswer", "Home", new { id = item.Id })" class="quesLink">
                        <span id="c" style="color:green;">@Html.DisplayFor(m => item.Question)</span>


                    </a>
                </div>

                <div>
                    <b> Posted by </b>   <span id="homPostUsr">   @Html.DisplayFor(m => item.PostedBy)</span>,  <b>Posted date</b>  <span id="homPostUsr">  @Html.DisplayFor(modelItem => item.Posteddate)</span>&nbsp; <img src="data:image/jpg;base64,@Convert.ToBase64String(item.Image)" width="40" height="" class="img-circle" />

                </div>
            </td>
            <td>
                <span style="color:blue"> @Html.DisplayFor(m => item.Category)</span>

            </td>
            <td>
                @Html.DisplayFor(m => item.Views)
            </td>
            <td>
                @Html.DisplayFor(m => item.Answers)
            </td>
        </tr>
    }

</table>